sud_education_vote/urls.py
from django.contrib import admin
from django.contrib.auth.views import (
    LogoutView,
    PasswordChangeDoneView,
    PasswordChangeView,
    PasswordResetCompleteView,
    PasswordResetConfirmView,
    PasswordResetDoneView,
    PasswordResetView,
)
from django.urls import include, path

from .views import AccueilView, ConnexionView

urlpatterns = [
    path("", AccueilView.as_view(), name="accueil"),
    path(
        "connexion/",
        ConnexionView.as_view(),
        name="connexion",
    ),
    path(
        "connexion/password_reset/",
        PasswordResetView.as_view(template_name="reinitialisation_password.html"),
        name="password_reset",
    ),
    path(
        "connexion/password_reset_done/",
        PasswordResetDoneView.as_view(
            template_name="reinitialisation_password_done.html"
        ),
        name="password_reset_done",
    ),
    path(
        "connexion/password_reset/confirm/<uidb64>/<token>/",
        PasswordResetConfirmView.as_view(
            template_name="reinitialisation_password_confirm.html"
        ),
        name="password_reset_confirm",
    ),
    path(
        "connexion/password_reset/done/",
        PasswordResetCompleteView.as_view(
            template_name="reinitialisation_password_complete.html"
        ),
        name="password_reset_complete",
    ),
    path(
        "deconnexion/",
        LogoutView.as_view(template_name="deconnexion.html"),
        name="deconnexion",
    ),
    path("admin/", admin.site.urls),
    path("utilisateurs/", include("sud_education_vote.utilisateur.urls")),
    path("votes/", include("sud_education_vote.vote.urls")),
    path("logs/", include("sud_education_vote.log.urls")),
    path(
        "changement-mot-de-passe/",
        PasswordChangeView.as_view(template_name="changement_pwd.html"),
        name="password_change",
    ),
    path(
        "changement-mot-de-passe-success/",
        PasswordChangeDoneView.as_view(template_name="changement_pwd_succes.html"),
        name="password_change_done",
    ),
]

sud_education_vote/vote/urls.py
from django.urls import path

from .views import (
    AdminVoteCreateView,
    ExportAllCSVResultatView,
    ExportCSVResultatView,
    ExportTxTMesVotesView,
    MesVotesView,
    PropositionCreateView,
    RedirectVoteCreateView,
    RedirectVoteUpdateView,
    ScrutinCreateView,
    ScrutinDetailView,
    ScrutinFermetureView,
    ScrutinListView,
    SuperAdminResetView,
    VoteCreateView,
    VoteDelegueCreateView,
    VoteOppositionCreateView,
    VoteOppositionUpdateView,
    VotePriorisationCreateView,
    VotePriorisationUpdateView,
    VoteUpdateView,
)

app_name = "vote"

urlpatterns = [
    path("", RedirectVoteCreateView.as_view(), name="page-vote"),
    path("vote/", VoteCreateView.as_view(), name="page-vote-simple"),
    path(
        "vote-opposition/",
        VoteOppositionCreateView.as_view(),
        name="page-vote-opposition",
    ),
    path(
        "vote-priorisation/",
        VotePriorisationCreateView.as_view(),
        name="page-vote-priorisation",
    ),
    path("vote/admin/", AdminVoteCreateView.as_view(), name="page-vote-admin"),
    path("mes-votes/", MesVotesView.as_view(), name="mes-votes"),
    path("mes-votes/export/", ExportTxTMesVotesView.as_view(), name="mes-votes-export"),
    path("scrutins/", ScrutinListView.as_view(), name="scrutins"),
    path("scrutins/creation/", ScrutinCreateView.as_view(), name="scrutin-creation"),
    path(
        "scrutins/<int:pk>/",
        ScrutinDetailView.as_view(),
        name="scrutin-detail",
    ),
    path(
        "scrutins/<int:pk>/export/",
        ExportCSVResultatView.as_view(),
        name="scrutin-export",
    ),
    path(
        "scrutins/export/",
        ExportAllCSVResultatView.as_view(),
        name="scrutins-export",
    ),
    path(
        "scrutins/<int:scrutin>/vote/<int:pk>/update/",
        RedirectVoteUpdateView.as_view(),
        name="vote-modification",
    ),
    path(
        "scrutins/<int:scrutin>/vote-simple/<int:pk>/update/",
        VoteUpdateView.as_view(),
        name="vote-simple-modification",
    ),
    path(
        "scrutins/<int:scrutin>/vote-opposition/<int:pk>/update/",
        VoteOppositionUpdateView.as_view(),
        name="vote-opposition-modification",
    ),
    path(
        "scrutins/<int:scrutin>/vote-priorisation/<int:pk>/update/",
        VotePriorisationUpdateView.as_view(),
        name="vote-priorisation-modification",
    ),
    path(
        "scrutins/<int:pk>/fermeture/",
        ScrutinFermetureView.as_view(),
        name="scrutin-fermeture",
    ),
    path(
        "scrutins/<int:pk>/vote-delegue/",
        VoteDelegueCreateView.as_view(),
        name="scrutin-delegue",
    ),
    path(
        "scrutins/<int:pk>/add-propositions/",
        PropositionCreateView.as_view(),
        name="scrutin-propositions",
    ),
    path(
        "reinitialisation/",
        SuperAdminResetView.as_view(),
        name="reinitialisation",
    ),
]

sud_education_vote/vote/models.py
from django.db import models
from django.db.models import Count, Sum
from django.utils.translation import gettext_lazy as _

from sud_education_vote.utilisateur.models import Utilisateur


class Scrutin(models.Model):
    """
    Scrutin pouvant être créé par un admin.
    - Contient un intitulé et un type
    - Si le type est Majorité ou majorité a deux tiers, les syndicats
    votes et attribuent leurs mandats sur l'application
    - Si le type est Délégué, les délégués votent a main levé et un
    admin rentre le resultat dans l'application, sur la page du scrutin
    - Possede une clef vers l'admin l'ayant ouvert
    """

    MAJORITE = "MAJORITE"
    MAJORITE_DEUX_TIERS = "MAJORITE_DEUX_TIERS"
    DELEGUE = "DELEGUE"
    MAJORITE_SYNDICATS = "MAJORITE_SYNDICATS"
    MAJORITE_SYNDICATS_OPPOSITION = "MAJORITE_SYNDICATS_OPPOSITION"
    MAJORITE_SYNDICATS_PRIORISATION = "MAJORITE_SYNDICATS_PRIORISATION"

    TYPES = [
        (MAJORITE, _("Majorité des syndicats et mandats")),
        (MAJORITE_DEUX_TIERS, _("Majorité des 2/3 des syndicats et mandats")),
        (DELEGUE, _("Majorité simple des délégué⋅es")),
        (MAJORITE_SYNDICATS, _("Majorité simple des syndicats")),
        (MAJORITE_SYNDICATS_OPPOSITION, _("Majorité des syndicats - Opposition")),
        (MAJORITE_SYNDICATS_PRIORISATION, _("Majorité des syndicats - Priorisation")),
    ]
    type_scrutin = models.CharField(
        choices=TYPES, max_length=max([len(e[0]) for e in TYPES])
    )
    intitule = models.CharField(max_length=255)

    createur = models.ForeignKey(
        Utilisateur,
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        related_name="scrutins",
    )

    ouvert = models.BooleanField(default=True)
    adoption = models.BooleanField(default=False)

    def __str__(self):
        return self.intitule

    @property
    def resultat(self):
        if self.ouvert:
            return "En cours"
        if self.type_scrutin in [
            Scrutin.MAJORITE_SYNDICATS_OPPOSITION,
            Scrutin.MAJORITE_SYNDICATS_PRIORISATION,
        ]:
            propositions = self.propositions.all()
            if self.type_scrutin == Scrutin.MAJORITE_SYNDICATS_OPPOSITION:
                if self.votes_opposition.count() == 0:
                    return _("Pas de votes")
                propositions = propositions.annotate(
                    sum_votes=Count("votes_opposition")
                ).order_by("-sum_votes", "text")
            elif self.type_scrutin == Scrutin.MAJORITE_SYNDICATS_PRIORISATION:
                if self.votes_priorisation.count() == 0:
                    return _("Pas de votes")
                propositions = propositions.annotate(
                    sum_votes=Sum("votes_propositions__score")
                ).order_by("-sum_votes", "text")
            winning_propositions = []
            max_votes = propositions[0].sum_votes
            for proposition in propositions:
                if proposition.sum_votes == max_votes:
                    winning_propositions.append(proposition.text)
            if len(winning_propositions) >= 2:
                return "Egalité entre plusieurs propositions : " + ", ".join(
                    winning_propositions
                )
            return str(winning_propositions[0])
        else:
            if self.votes.count() == 0:
                return _("Pas de votes")
            elif self.adoption:
                return _("Adopté")
            else:
                return _("Rejeté")

    @property
    def resultat_syndicats(self):
        if self.ouvert:
            return "En cours"
        pour = 0
        contre = 0
        abstention = 0
        nppv = 0
        for vote in self.votes.all():
            if vote.vote_utilisateur == Vote.POUR:
                pour = pour + 1
            elif vote.vote_utilisateur == Vote.CONTRE:
                contre = contre + 1
            elif vote.vote_utilisateur == Vote.ABSTENTION:
                abstention = abstention + 1
            elif vote.vote_utilisateur == Vote.NPPV:
                nppv = nppv + 1
        resultats = f"P: {pour}\n" f"C: {contre}\n" f"A: {abstention}\n" f"N: {nppv}"
        return resultats

    @property
    def resultat_syndicats_opposition(self):
        if self.ouvert:
            return "En cours"
        resultats = ""
        propositions = (
            self.propositions.all()
            .annotate(count_votes=Count("votes_opposition"))
            .order_by("-count_votes")
        )
        for proposition in propositions:
            resultats += f"{proposition.text} : {proposition.count_votes or 0}\n"
        nb_abstention = VoteOpposition.objects.filter(
            scrutin=self, abstention=True
        ).count()
        nb_nppv = VoteOpposition.objects.filter(scrutin=self, nppv=True).count()
        resultats += f"Abstention : {nb_abstention}\n"
        resultats += f"Nppv : {nb_nppv}\n"
        return resultats

    @property
    def resultat_syndicats_priorisation(self):
        if self.ouvert:
            return "En cours"
        resultats = ""
        propositions = (
            self.propositions.all()
            .annotate(sum_scores=Sum("votes_propositions__score"))
            .order_by("-sum_scores")
        )
        for proposition in propositions:
            resultats += f"{proposition.text} : {proposition.sum_scores or 0}\n"
        nb_abstention = VotePriorisation.objects.filter(
            scrutin=self, abstention=True
        ).count()
        nb_nppv = VotePriorisation.objects.filter(scrutin=self, nppv=True).count()
        resultats += f"Abstention : {nb_abstention}\n"
        resultats += f"Nppv : {nb_nppv}\n"
        return resultats

    @property
    def resultat_mandats(self):
        if self.ouvert:
            return "En cours"
        pour = 0
        contre = 0
        abstention = 0
        nppv = 0
        for vote in self.votes.all():
            pour = pour + vote.mandats_pour
            contre = contre + vote.mandats_contre
            abstention = abstention + vote.mandats_abstention
            nppv = nppv + vote.mandats_nppv
        resultats = f"P: {pour}\n" f"C: {contre}\n" f"A: {abstention}\n" f"N: {nppv}"
        return resultats

    @property
    def type_scrutin_display(self):
        if self.type_scrutin == self.MAJORITE:
            return _("Majorité des syndicats et mandats")
        elif self.type_scrutin == self.MAJORITE_DEUX_TIERS:
            return _("Majorité des 2/3 des syndicats et mandats")
        elif self.type_scrutin == self.MAJORITE_SYNDICATS:
            return _("Majorité simple des syndicats")
        elif self.type_scrutin == self.MAJORITE_SYNDICATS_OPPOSITION:
            return _("Majorité des syndicats - Opposition")
        elif self.type_scrutin == self.MAJORITE_SYNDICATS_PRIORISATION:
            return _("Majorité des syndicats - Priorisation")
        else:
            return _("Majorité simple des délégué⋅es")

    """
        Cette méthode est utilisée uniquement pour les votes simples
        visant l'adoption ou non d'une mesure.
        Cela exclut les scrutins de type
        "Majorité des syndicats - Opposition"
        et "Majorité des syndicats - Priorisation"
    """

    def calcul_resultat(self):
        votes = self.votes.all()
        syndicat_pour = votes.filter(vote_utilisateur="POUR").count()
        syndicat_contre = votes.filter(vote_utilisateur="CONTRE").count()
        syndicat_abst = votes.filter(vote_utilisateur="ABSTENTION").count()
        mandats_pour = sum([vote.mandats_pour for vote in votes])
        mandats_contre = sum([vote.mandats_contre for vote in votes])
        mandats_abstention = sum([vote.mandats_abstention for vote in votes])

        adoption_syndicats = False
        adoption_mandats = False

        if votes.count() > 0:
            if self.type_scrutin == Scrutin.MAJORITE:
                if syndicat_pour > syndicat_contre + syndicat_abst:
                    adoption_syndicats = True
                if mandats_pour > mandats_contre + mandats_abstention:
                    adoption_mandats = True
            elif self.type_scrutin == Scrutin.MAJORITE_DEUX_TIERS:
                if (
                    syndicat_pour
                    >= (syndicat_pour + syndicat_contre + syndicat_abst) * 2 / 3
                ):
                    adoption_syndicats = True
                if (
                    mandats_pour
                    >= (mandats_pour + mandats_contre + mandats_abstention) * 2 / 3
                ):
                    adoption_mandats = True
            elif self.type_scrutin == Scrutin.MAJORITE_SYNDICATS:
                if syndicat_pour > syndicat_contre + syndicat_abst:
                    adoption_syndicats = True
                    adoption_mandats = True
            else:
                if mandats_pour > mandats_contre + mandats_abstention:
                    adoption_syndicats = True
                    adoption_mandats = True

        self.adoption = adoption_syndicats and adoption_mandats
        self.save()

    class Meta:
        verbose_name = _("Scrutin")
        verbose_name_plural = _("Scrutins")


class Proposition(models.Model):
    """
    Proposition  pour les scrutins à majorité par syndicats uniquement.
    Le type d'adoption est lié au type de scrutin choisi :
    - Type MAJORITE_SYNDICALES_OPPOSITION :
    l'utilisateur choisit une unique proposition parmi celles proposées
    - Type MAJORITE_SYNDICALES_PRIORISATION:
    l'utilisateur classe les propositions
    """

    text = models.CharField(max_length=255)
    scrutin = models.ForeignKey(
        Scrutin, on_delete=models.CASCADE, related_name="propositions"
    )

    def __str__(self):
        return self.text


class Vote(models.Model):
    """
    Vote pouvant être créé par un admin, ou un syndicat.
    - Lié à un scrutin, et à un utilisateur
    - Si l'utilisateur est un syndicat, il répartit ses mandats entre Pour,

sud_education_vote/vote/templates/vote/add_propositions.html
{% extends 'base.html' %}

{% load bulma_tags i18n static %}

{% block content %}

<div class="container is-fluid">
  <div class="has-text-centered">
    <a class="button is-info is-rounded is-outlined" href="{% url 'vote:scrutins' %}">
      {% trans "Retour à la liste des scrutins" %}
    </a>
  </div>
  <section class="section">
    <div class="columns is-centered is-desktop">
      <div class="column is-half-desktop">
        <h1 class="title has-text-centered">{% trans "Ajout de propositions" %}</h1>
        <div class="box">
          <form class="form" method="post">
            {% csrf_token %}
            <div class="field prop">
                <label for="id_text" class="label">Proposition</label>
                <div class="control">
                  <input type="text" name="proposition" maxlength="255" class="control input" required="" id="id_text">
                </div>
            </div>
              <div class="field prop">
                <label for="id_text" class="label">Proposition</label>
                <div class="control">
                  <input type="text" name="proposition" maxlength="255" class="control input" required="" id="id_text">
                </div>
            </div>
            <div class="fields-container">
            </div>
              <p id="add-button" class="is-clickable my-3"><i class="fa fa-plus mr-2" aria-hidden="true"></i>Ajouter une proposition</p>
              <p id="delete-button" class="is-clickable my-3"><i class="fa fa-minus mr-2" aria-hidden="true"></i>Supprimer la dernière proposition</p>
            <div class="field has-text-centered">
              <button id="button-validation" class="button is-success is-rounded is-outlined" type="submit">{% trans "Valider" %}</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </section>
</div>

<script>
validation = document.getElementById("button-validation")
validation.disabled = true

addButton = document.getElementById("add-button")
deleteButton = document.getElementById("delete-button")

fieldsContainer = document.querySelector(".fields-container")
prop = document.querySelector('.prop');
count = 2

propositions = document.querySelectorAll('.input');
propositions.forEach(proposition => {
  proposition.addEventListener('change', event => {
    verificationForm()
  })
})

function verificationForm(){
  propositions = document.querySelectorAll('.input');
  erreur = document.getElementById("erreur")
  if (erreur) {
    erreur.remove()
  }
  for(var i=0;i<propositions.length;i++){
    if (propositions[i].value === "") {
      validation.closest(".form").insertAdjacentHTML(
        'afterbegin',
        `<div id="erreur" class="mb-2"><span class="help is-danger ">{% trans "Toutes les propositions doivent contenir un texte." %}</span></div>`
      )
      validation.disabled = true
      return
    }
  }
  validation.disabled = false
}

validation.addEventListener('click', () => {
  if(!validation.disabled){
    validation.classList.replace("is-outlined", "is-loading")
  }
})

addButton.addEventListener('click', () => {
  new_prop = prop.cloneNode(true)
  new_prop.children[1].children[0].id=`id_text${count}`
  count++
  new_prop.children[1].children[0].value=""
  new_prop.addEventListener('change', event => {
    verificationForm()
  })
  fieldsContainer.appendChild(new_prop)
  verificationForm()
})

deleteButton.addEventListener('click', () => {
  lastField = fieldsContainer.lastElementChild
  if (lastField !== null){
    lastField.remove()
  }
  verificationForm()
})

</script>

{% endblock %}

sud_education_vote/vote/templates/vote/admin_creation_vote.html
{% extends 'base.html' %}

{% load bulma_tags i18n static %}

{% block content %}

<div class="container is-fluid">
  <section class="section">
    <h1 class="title has-text-centered">
        {% trans "Choix du syndicat pour lequel vous allez voter" %}
    </h1>
    <div class="columns is-centered is-desktop">
      <div class="column is-half-desktop">
          <div class="box">
            <form class="form fullwidth" method="post">
              {% csrf_token %}
              {{ form|bulma}}
              <div class="field has-text-centered">
                <button id="button_validation" class="button is-success is-rounded is-outlined" type="submit">{% trans "Valider" %}</button>
              </div>
            </form>
          </div>
      </div>
    </div>
  </section>
</div>

{% endblock %}

sud_education_vote/vote/templates/vote/creation_scrutin.html
{% extends 'base.html' %}

{% load bulma_tags i18n static %}

{% block content %}

<div class="container is-fluid">
  <div class="has-text-centered">
    <a class="button is-info is-rounded is-outlined" href="{% url 'vote:scrutins' %}">
      {% trans "Retour à la liste des scrutins" %}
    </a>
  </div>
  <section class="section">
    <div class="columns is-centered is-desktop">
      <div class="column is-half-desktop">
        <h1 class="title has-text-centered">{% trans "Création de scrutin" %}</h1>
        <div class="box">
          <form class="form" method="post">
            {% csrf_token %}
            {{ form|bulma}}
            <div class="field has-text-centered">
              <button class="button is-success is-rounded is-outlined" type="submit">{% trans "Valider" %}</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </section>
</div>

{% endblock %}

sud_education_vote/vote/templates/vote/creation_vote_delegue.html
{% extends 'base.html' %}

{% load bulma_tags i18n static %}

{% block content %}

<div class="container is-fluid">
  <div class="has-text-centered">
    <a class="button is-info is-rounded is-outlined" href="{% url 'vote:scrutins' %}">
      {% trans "Retour à la liste des scrutins" %}
    </a>
  </div>
  <section class="section">
    <div class="columns is-centered is-desktop">
      <div class="column is-half-desktop">
        <h1 class="title has-text-centered">{% trans "Vote par délégués" %}</h1>
        <div class="box">
          <form class="form" method="post">
            {% csrf_token %}
            {{ form|bulma}}
            <div class="field has-text-centered">
              <button class="button is-success is-rounded is-outlined" type="submit">{% trans "Valider" %}</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </section>
</div>

{% endblock %}

sud_education_vote/vote/templates/vote/detail_scrutin.html
{% extends 'base.html' %}

{% load i18n static %}

{% block content %}

<div class="container is-fluid">
    <div class="has-text-centered">
        <a class="button is-info is-rounded is-outlined" href="{% url 'vote:scrutins' %}">
            {% trans "Retour à la liste des scrutins" %}
        </a>
    </div>

    <div class="columns is-centered">
        <div class="column is-full">
            <div class="box m-6 has-text-centered">
                <h1 class="title has-text-centered">{{object.intitule}}</h1>
                <h2 class="subtitle has-text-centered">
                    {{object.type_scrutin_display}}
                </h2>
                <h2 class="subtitle has-text-centered">
                    {% if object.ouvert %}
                        {% trans "En cours" %}
                    {% else %}
                        {% if opposition or priorisation %}
                            {{ object.resultat }}
                        {% elif object.adoption %}
                            {% trans "Adopté" %}
                        {% else %}
                            {% trans "Rejeté" %}
                        {% endif %}
                    {% endif %}
                </h2>
            </div>
            {% if votes %}
            <div>
                <a class="button is-success is-rounded is-outlined" href="{% url 'vote:scrutin-export' pk=object.pk %}">
                    {% trans "Export csv" %}
                </a>
            </div>
            <div class="table-container">
                <table class="table table-center is-fullwidth">
                    <thead>
                        <tr>
                            <th>{% trans "Syndicat" %}</th>
                            <th>{% trans "Vote du syndicat" %}</th>
                            {% if not majorite_syndicats%}
                                <th>{% trans "Mandats pour" %}</th>
                                <th>{% trans "Mandats contre" %}</th>
                                <th>{% trans "Mandats abstention" %}</th>
                                <th>{% trans "Mandats NPPV" %}</th>
                            {% endif %}
                            {% if user.is_admin %}
                            <th>{% trans "Action" %}</th>
                            {% endif %}
                        </tr>
                    </thead>
                    <tbody>
                    {% for vote in votes %}
                        <tr>
                            {% if opposition or priorisation %}
                                <td>{{vote.utilisateur}}</td>
                                <td>{{vote.resultat}}</td>
                            {% elif majorite_syndicats %}
                                <td>{{vote.utilisateur}}</td>
                                <td>{{vote.vote_utilisateur}}</td>
                            {% else %}
                            <td>{{vote.utilisateur}}</td>
                                <td>{{vote.vote_utilisateur}}</td>
                                <td>{{vote.mandats_pour}}</td>
                                <td>{{vote.mandats_contre}}</td>
                                <td>{{vote.mandats_abstention}}</td>
                                <td>{{vote.mandats_nppv}}</td>
                            {% endif %}

                            {% if user.is_admin %}
                                <td>
                                {% if opposition %}
                                    <a class="button is-warning" href="{% url 'vote:vote-opposition-modification' scrutin=object.pk pk=vote.pk %}">{% trans "Modifier" %}</a>
                                {% elif priorisation %}
                                    <a class="button is-warning" href="{% url 'vote:vote-priorisation-modification' scrutin=object.pk pk=vote.pk %}">{% trans "Modifier" %}</a>
                                {% else %}
                                    <a class="button is-warning" href="{% url 'vote:vote-simple-modification' scrutin=object.pk pk=vote.pk %}">{% trans "Modifier" %}</a>
                                {% endif %}
                                </td>
                            {% endif %}
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
            {% else %}
            <h2 class="subtitle has-text-centered">
                {% trans "Il n'y a pas eu de vote pour ce scrutin!" %}
            </h2>
            {% endif %}
        </div>
    </div>
</div>

{% endblock %}

sud_education_vote/vote/templates/vote/liste_scrutins.html
{% extends 'base.html' %}

{% load i18n static %}

{% block content %}

<div class="container is-fluid">
    <section class="section">
        <h1 class="title has-text-centered">
            {% if user.is_admin %}
            {% trans "Liste des scrutins" %}
            {% else %}
            {% trans "Scrutins passés" %}
            {% endif %}
        </h1>
        <div class="columns is-centered">
            <div class="column is-full">
                {% if user.is_admin %}
                <div class="box m-6 has-text-centered">
                    <h2 class="title is-4 has-text-centered">{% trans "Scrutin actuel :" %}</h2>
                    {% if scrutin_actuel %}
                    <p class="title is-5">
                        {% if scrutin_actuel.type_scrutin == 'DELEGUE' %}
                        <a href="{% url 'vote:scrutin-delegue' pk=scrutin_actuel.pk %}">{{scrutin_actuel.intitule}}</a>
                        {% else %}
                        {{scrutin_actuel.intitule}}
                        {% endif %}
                    </p>
                    <p class="subtitle">{{scrutin_actuel.type_scrutin_display}}</p>
                    <p class="subtitle">{% trans "Nombre de syndicats n'ayant pas voté:" %} <strong>{{nombre_syndicats_non_vote}}</strong></p>
                    <div class="has-text-centered mb-2">
                        <a class="button is-info is-rounded is-outlined" href="{% url 'vote:scrutins' %}">
                          <span class="icon">
                            <i class="fa fa-refresh" aria-hidden="true"></i>
                          </span>
                          <span>
                            {% trans "Actualiser" %}
                          </span>
                        </a>
                      </div>
                    <a class="button is-danger is-rounded is-outlined" href="{% url 'vote:scrutin-fermeture' pk=scrutin_actuel.pk %}">
                        {% trans "Fermer le scrutin" %}
                    </a>
                    {% else %}
                    <p>{% trans "Il n'y a pas de scrutin actuellement ouvert" %}</p>
                    <a class="mt-2 button is-success is-rounded is-outlined" href="{% url 'vote:scrutin-creation' %}">
                        {% trans "Ouvrir un scrutin" %}
                    </a>
                    {% endif %}
                </div>
                {% endif %}
                {% if object_list %}
                <div>
                    <a class="button is-success is-rounded is-outlined" href="{% url 'vote:scrutins-export' %}">
                        {% trans "Export scrutins csv" %}
                    </a>
                </div>
                <div class="table-container">
                    <table class="table table-center is-fullwidth">
                        <thead>
                            <tr>
                                <th>{% trans "Intitulé" %}</th>
                                <th>{% trans "Type" %}</th>
                                <th>{% trans "Résultat" %}</th>
                                <th>{% trans "Votes syndicats" %}</th>
                                <th>{% trans "Votes mandats" %}</th>
                            </tr>
                        </thead>
                        <tbody>
                      {% for scrutin in object_list %}
                            <tr>
                                <td>
                                    <a href="{% url 'vote:scrutin-detail' pk=scrutin.pk %}" aria-label="Voir le détail du scrutin">
                                        {{scrutin.intitule}}
                                        <span class="icon">
                                            <i class="fa fa-bars"></i>
                                        </span>
                                    </a>
                                </td>
                                <td>{{scrutin.type_scrutin_display}}</td>
                                <td>
                                    {{scrutin.resultat}}
                                </td>
                                <td>
                                    {% if scrutin.type_scrutin == "MAJORITE_SYNDICATS_OPPOSITION" %}
                                        {{scrutin.resultat_syndicats_opposition|linebreaksbr}}
                                    {% elif scrutin.type_scrutin == "MAJORITE_SYNDICATS_PRIORISATION" %}
                                        {{scrutin.resultat_syndicats_priorisation|linebreaksbr}}
                                    {% elif scrutin.type_scrutin != "DELEGUE"%}
                                        {{scrutin.resultat_syndicats|linebreaksbr}}
                                    {% endif %}
                                </td>
                                <td>
                                    {% if scrutin.type_scrutin != "MAJORITE_SYNDICATS_OPPOSITION" and scrutin.type_scrutin != "MAJORITE_SYNDICATS" and scrutin.type_scrutin != "MAJORITE_SYNDICATS_PRIORISATION" %}
                                        {{scrutin.resultat_mandats|linebreaksbr}}
                                    {% endif %}
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
                {% else %}
                <h2 class="title is-5 has-text-centered">
                    {% trans "Il n'y a pas encore eu de scrutins!" %}
                </h2>
                {% endif %}
            </div>
        </div>
    </section>
</div>

{% endblock %}