sud_education_vote/log/urls.py
from django.urls import path

from .views import ExportTxtJournalView, JournalLogListView

app_name = "log"

urlpatterns = [
    path("journal/", JournalLogListView.as_view(), name="journal"),
    path("journal/export/", ExportTxtJournalView.as_view(), name="journal-export"),
]

sud_education_vote/urls.py
from django.contrib import admin
from django.contrib.auth.views import (
    LogoutView,
    PasswordChangeDoneView,
    PasswordChangeView,
    PasswordResetCompleteView,
    PasswordResetConfirmView,
    PasswordResetDoneView,
    PasswordResetView,
)
from django.urls import include, path

from .views import AccueilView, ConnexionView

urlpatterns = [
    path("", AccueilView.as_view(), name="accueil"),
    path(
        "connexion/",
        ConnexionView.as_view(),
        name="connexion",
    ),
    path(
        "connexion/password_reset/",
        PasswordResetView.as_view(template_name="reinitialisation_password.html"),
        name="password_reset",
    ),
    path(
        "connexion/password_reset_done/",
        PasswordResetDoneView.as_view(
            template_name="reinitialisation_password_done.html"
        ),
        name="password_reset_done",
    ),
    path(
        "connexion/password_reset/confirm/<uidb64>/<token>/",
        PasswordResetConfirmView.as_view(
            template_name="reinitialisation_password_confirm.html"
        ),
        name="password_reset_confirm",
    ),
    path(
        "connexion/password_reset/done/",
        PasswordResetCompleteView.as_view(
            template_name="reinitialisation_password_complete.html"
        ),
        name="password_reset_complete",
    ),
    path(
        "deconnexion/",
        LogoutView.as_view(template_name="deconnexion.html"),
        name="deconnexion",
    ),
    path("admin/", admin.site.urls),
    path("utilisateurs/", include("sud_education_vote.utilisateur.urls")),
    path("votes/", include("sud_education_vote.vote.urls")),
    path("logs/", include("sud_education_vote.log.urls")),
    path(
        "changement-mot-de-passe/",
        PasswordChangeView.as_view(template_name="changement_pwd.html"),
        name="password_change",
    ),
    path(
        "changement-mot-de-passe-success/",
        PasswordChangeDoneView.as_view(template_name="changement_pwd_succes.html"),
        name="password_change_done",
    ),
]

sud_education_vote/utilisateur/urls.py
from django.urls import path

from .views import (
    AdminCreationView,
    AdminListView,
    AdminSupressionView,
    AdminUpdateView,
    ImportMandatsView,
    SyndicatCreateView,
    SyndicatListView,
    SyndicatSuppressionView,
    SyndicatUpdateView,
)

app_name = "utilisateur"

urlpatterns = [
    path("admins/", AdminListView.as_view(), name="admins"),
    path("admins/creation/", AdminCreationView.as_view(), name="admin-creation"),
    path(
        "admins/<int:pk>/edition/",
        AdminUpdateView.as_view(),
        name="admin-edition",
    ),
    path(
        "admins/<int:pk>/suppression/",
        AdminSupressionView.as_view(),
        name="admin-supression",
    ),
    path("syndicats/", SyndicatListView.as_view(), name="syndicats"),
    path("syndicats/creation/", SyndicatCreateView.as_view(), name="syndicat-creation"),
    path(
        "syndicats/<int:pk>/edition/",
        SyndicatUpdateView.as_view(),
        name="syndicat-edition",
    ),
    path(
        "syndicats/<int:pk>/suppression/",
        SyndicatSuppressionView.as_view(),
        name="syndicat-suppression",
    ),
    path("import-mandats/", ImportMandatsView.as_view(), name="import-mandats"),
]

sud_education_vote/vote/urls.py
from django.urls import path

from .views import (
    AdminVoteCreateView,
    ExportAllCSVResultatView,
    ExportCSVResultatView,
    ExportTxTMesVotesView,
    MesVotesView,
    PropositionCreateView,
    RedirectVoteCreateView,
    RedirectVoteUpdateView,
    ScrutinCreateView,
    ScrutinDetailView,
    ScrutinFermetureView,
    ScrutinListView,
    SuperAdminResetView,
    VoteCreateView,
    VoteDelegueCreateView,
    VoteOppositionCreateView,
    VoteOppositionUpdateView,
    VotePriorisationCreateView,
    VotePriorisationUpdateView,
    VoteUpdateView,
)

app_name = "vote"

urlpatterns = [
    path("", RedirectVoteCreateView.as_view(), name="page-vote"),
    path("vote/", VoteCreateView.as_view(), name="page-vote-simple"),
    path(
        "vote-opposition/",
        VoteOppositionCreateView.as_view(),
        name="page-vote-opposition",
    ),
    path(
        "vote-priorisation/",
        VotePriorisationCreateView.as_view(),
        name="page-vote-priorisation",
    ),
    path("vote/admin/", AdminVoteCreateView.as_view(), name="page-vote-admin"),
    path("mes-votes/", MesVotesView.as_view(), name="mes-votes"),
    path("mes-votes/export/", ExportTxTMesVotesView.as_view(), name="mes-votes-export"),
    path("scrutins/", ScrutinListView.as_view(), name="scrutins"),
    path("scrutins/creation/", ScrutinCreateView.as_view(), name="scrutin-creation"),
    path(
        "scrutins/<int:pk>/",
        ScrutinDetailView.as_view(),
        name="scrutin-detail",
    ),
    path(
        "scrutins/<int:pk>/export/",
        ExportCSVResultatView.as_view(),
        name="scrutin-export",
    ),
    path(
        "scrutins/export/",
        ExportAllCSVResultatView.as_view(),
        name="scrutins-export",
    ),
    path(
        "scrutins/<int:scrutin>/vote/<int:pk>/update/",
        RedirectVoteUpdateView.as_view(),
        name="vote-modification",
    ),
    path(
        "scrutins/<int:scrutin>/vote-simple/<int:pk>/update/",
        VoteUpdateView.as_view(),
        name="vote-simple-modification",
    ),
    path(
        "scrutins/<int:scrutin>/vote-opposition/<int:pk>/update/",
        VoteOppositionUpdateView.as_view(),
        name="vote-opposition-modification",
    ),
    path(
        "scrutins/<int:scrutin>/vote-priorisation/<int:pk>/update/",
        VotePriorisationUpdateView.as_view(),
        name="vote-priorisation-modification",
    ),
    path(
        "scrutins/<int:pk>/fermeture/",
        ScrutinFermetureView.as_view(),
        name="scrutin-fermeture",
    ),
    path(
        "scrutins/<int:pk>/vote-delegue/",
        VoteDelegueCreateView.as_view(),
        name="scrutin-delegue",
    ),
    path(
        "scrutins/<int:pk>/add-propositions/",
        PropositionCreateView.as_view(),
        name="scrutin-propositions",
    ),
    path(
        "reinitialisation/",
        SuperAdminResetView.as_view(),
        name="reinitialisation",
    ),
]

sud_education_vote/log/views/log_journal_view.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.views.generic import ListView, View

from sud_education_vote.vote.models import Scrutin

from ..models import Log


class JournalLogListView(LoginRequiredMixin, ListView):
    template_name = "log/journal_logs.html"
    model = Log

    def dispatch(self, request, *args, **kwargs):
        scrutin_en_cours = Scrutin.objects.filter(ouvert=True).exists()
        if scrutin_en_cours:
            if not self.request.user.is_admin:
                messages.add_message(
                    self.request,
                    messages.ERROR,
                    (
                        "Un scrutin est en cours, vous ne pouvez"
                        " pas consulter les logs !"
                    ),
                )
                return HttpResponseRedirect(reverse("vote:scrutins"))
        return super().dispatch(request, *args, **kwargs)

    # On affiche les 200 derniers Logs
    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.order_by("-date_log")[:200]
        return queryset


class ExportTxtJournalView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        content = ""
        for log in Log.objects.all():
            date_str = log.date_log.strftime("%m/%d/%Y %H:%M:%S")
            content = content + f"{date_str} {log.log}\n"
        response = HttpResponse(
            content=content,
            content_type="text/plain",
            headers={"Content-Disposition": "attachment; filename=journal.txt"},
        )
        return response

sud_education_vote/utilisateur/views/gestion_admin_views.py
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views.generic import CreateView, DeleteView, ListView, UpdateView

from sud_education_vote.log.models import Log
from sud_education_vote.mixins import SuperAdminRequisMixin

from ..forms import AdminCreationForm, AdminUpdateForm
from ..models import Utilisateur


class AdminListView(SuperAdminRequisMixin, ListView):
    template_name = "utilisateur/liste_admins.html"
    model = Utilisateur

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(type_utilisateur=Utilisateur.ADMIN)
        return queryset


class AdminCreationView(SuperAdminRequisMixin, CreateView):
    model = Utilisateur
    form_class = AdminCreationForm
    template_name = "utilisateur/creation_admin.html"

    def form_valid(self, form):
        self.object = form.save()
        raw_password = self.object.password
        self.object.set_password(raw_password)
        self.object.type_utilisateur = Utilisateur.ADMIN
        self.object.save()
        Log.objects.create(log=f"Le super admin a créé l'admin {self.object}")
        return HttpResponseRedirect(self.get_success_url())

    def get_success_url(self):
        return reverse("utilisateur:admins")


class AdminUpdateView(SuperAdminRequisMixin, UpdateView):
    model = Utilisateur
    form_class = AdminUpdateForm
    template_name = "utilisateur/edition_admin.html"

    """
    On s'assure que l'utilisateur choisi est bien un admin
    """

    def get_queryset(self):
        return super().get_queryset().filter(type_utilisateur=Utilisateur.ADMIN)

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs.update({"user": self.get_object(), "update": True})
        return kwargs

    def get_success_url(self):
        return reverse("utilisateur:admins")


class AdminSupressionView(SuperAdminRequisMixin, DeleteView):
    model = Utilisateur
    template_name = "utilisateur/supression_admin.html"

    """
    On s'assure que l'utilisateur choisi est bien un admin
    """

    def get_queryset(self):
        return super().get_queryset().filter(type_utilisateur=Utilisateur.ADMIN)

    def delete(self, request, *args, **kwargs):
        Log.objects.create(log=f"Le super admin a supprimé l'admin {self.get_object()}")
        return super().delete(request, *args, **kwargs)

    def get_success_url(self):
        return reverse("utilisateur:admins")

sud_education_vote/utilisateur/views/gestion_syndicat_views.py
import codecs
import csv

from django.contrib import messages
from django.http import HttpResponseRedirect
from django.shortcuts import redirect, render
from django.urls import reverse
from django.views.generic import CreateView, DeleteView, ListView, UpdateView, View

from sud_education_vote.log.models import Log
from sud_education_vote.mixins import AdminRequisMixin

from ..forms import FichierImportMandatsForm, SyndicatForm
from ..models import Utilisateur


class SyndicatListView(AdminRequisMixin, ListView):
    template_name = "utilisateur/liste_syndicats.html"
    model = Utilisateur

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(type_utilisateur=Utilisateur.SYNDICAT)
        return queryset


class SyndicatCreateView(AdminRequisMixin, CreateView):
    model = Utilisateur
    template_name = "utilisateur/creation_syndicat.html"
    form_class = SyndicatForm

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs.update({"update": False, "user": None})
        return kwargs

    def get_success_url(self):
        return reverse("utilisateur:syndicats")

    def form_valid(self, form):
        self.object = form.save()
        self.object.type_utilisateur = Utilisateur.SYNDICAT
        self.object.save()
        Log.objects.create(
            log=f"L'admin {self.request.user} a créé le syndicat {self.object}"
        )
        return HttpResponseRedirect(self.get_success_url())


class SyndicatUpdateView(AdminRequisMixin, UpdateView):
    model = Utilisateur
    template_name = "utilisateur/edition_syndicat.html"
    form_class = SyndicatForm

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs.update({"update": True, "user": self.get_object()})
        return kwargs

    def get_queryset(self):
        return super().get_queryset().filter(type_utilisateur=Utilisateur.SYNDICAT)

    def get_success_url(self):
        return reverse("utilisateur:syndicats")

    def form_valid(self, form):
        previous_instance = Utilisateur.objects.get(pk=self.object.pk)
        self.object = form.save()
        if previous_instance.nombre_mandat != self.object.nombre_mandat:
            Log.objects.create(
                log=(
                    f"L'admin {self.request.user} a modifié "
                    f"le nombre de mandats du syndicat {self.object} "
                    f"de {previous_instance.nombre_mandat} à "
                    f"{self.object.nombre_mandat}"
                )
            )
        if previous_instance.email != self.object.email:
            Log.objects.create(
                log=(
                    f"L'admin {self.request.user} a modifié "
                    f"le mail du syndicat {self.object} "
                    f"de {previous_instance.email} à {self.object.email}"
                )
            )
        return HttpResponseRedirect(self.get_success_url())


class SyndicatSuppressionView(AdminRequisMixin, DeleteView):
    model = Utilisateur
    template_name = "utilisateur/suppression_syndicat.html"

    """
    On s'assure que l'utilisateur choisi est bien un syndicat
    """

    def get_queryset(self):
        return super().get_queryset().filter(type_utilisateur=Utilisateur.SYNDICAT)

    def delete(self, request, *args, **kwargs):
        Log.objects.create(
            log=f"L'admin {self.request.user} a "
            f"supprimé le syndicat {self.get_object()}"
        )
        return super().delete(request, *args, **kwargs)

    def get_success_url(self):
        return reverse("utilisateur:syndicats")


class ImportMandatsView(AdminRequisMixin, View):
    form_class = FichierImportMandatsForm
    template_name = "utilisateur/import_mandats.html"

    def get(self, request, *args, **kwargs):
        form = self.form_class()
        return render(request, self.template_name, {"form": form})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST, request.FILES)
        fichier = request.FILES["fichier"]
        if fichier.content_type == "text/csv":
            reader = csv.reader((codecs.iterdecode(fichier, "utf-8")))
            syndicats_erreur = []
            error = False
            for row in reader:
                if row[0] != "Syndicats":
                    syndicat = Utilisateur.objects.filter(
                        type_utilisateur=Utilisateur.SYNDICAT, username=row[0]
                    ).first()
                    if not syndicat or not row[1].isnumeric():
                        error = True
                        syndicats_erreur.append(row[0])
                    else:
                        syndicat.nombre_mandat = row[1]
                        syndicat.save()
            if error:
                messages.add_message(
                    self.request,
                    messages.WARNING,
                    (
                        f"Les lignes suivantes n'ont pas pu être ajoutées : "
                        f"{', '.join(syndicats_erreur)}. Vérifiez l'orthographe du nom"
                        f" du syndicat ou le nombre de mandats."
                    ),
                )
            return redirect(reverse("utilisateur:syndicats"))
        else:
            messages.add_message(
                self.request,
                messages.ERROR,
                ("Le fichier téléversé n'est pas au bon format"),
            )
            return render(request, self.template_name, {"form": form})

sud_education_vote/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView
from django.urls import reverse
from django.utils.http import url_has_allowed_host_and_scheme
from django.views.generic import TemplateView


class AccueilView(LoginRequiredMixin, TemplateView):
    template_name = "accueil.html"


class ConnexionView(LoginView):
    template_name = "connexion.html"
    default_url = ""

    def get_success_url(self):
        if self.request.user.is_superadmin:
            self.default_url = reverse("utilisateur:admins")
        elif self.request.user.is_admin:
            self.default_url = reverse("accueil")
        else:
            self.default_url = reverse("vote:page-vote")
        return super().get_success_url()

    def get_redirect_url(self):
        """Return the user-originating redirect URL if it's safe."""

        redirect_to = self.request.POST.get(
            self.redirect_field_name,
            self.request.GET.get(self.redirect_field_name, self.default_url),
        )
        url_is_safe = url_has_allowed_host_and_scheme(
            url=redirect_to,
            allowed_hosts=self.get_success_url_allowed_hosts(),
            require_https=self.request.is_secure(),
        )
        return redirect_to if url_is_safe else ""

sud_education_vote/templates/accueil.html
{% extends 'base.html' %}

{% load i18n %}

{% block content %}

<div class="container is-fluid">
  <section class="section">
    <div class="columns is-centered is-desktop mt-2">
      <div class="column is-half-desktop">
        <h1 class="title has-text-centered">Sud Education vote</h1>
        <h2 class="subtitle has-text-centered has-text-primary">{% trans "Bienvenue !" %}</h2>
        <h2 class="subtitle has-text-centered">{% trans "Vous êtes connecté⋅e en tant que" %} {{user}}</h2>
      </div>
    </div>
  </section>
</div>

{% endblock %}

sud_education_vote/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="utf-8" />
    <title>Sud Education Vote</title>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="icon" href="{% static 'images/icon.jpg' %}" />
    <link type="text/css" href="{% static 'css/bulma.min.css' %}" rel="stylesheet"/>
    <link type="text/css" href="{% static 'css/fork-awesome.min.css' %}" rel="stylesheet"/>
</head>

<body id="{{ self.slug }}-{{ self.id }}">
{% include 'menu.html' %}
{% include 'messages.html' %}
{% block content %}{% endblock %}
</body>
</html>

sud_education_vote/templates/changement_pwd.html
{% extends 'base.html' %}

{% load bulma_tags i18n %}

{% block content %}

<div class="container is-fluid">
  <section class="section">
    <div class="columns is-centered is-desktop mt-2">
      <div class="column is-half-desktop">
        <h1 class="title has-text-centered">{% trans "Changement de mot de passe" %}</h1>
        <div class="box">
          <form class="form" method="post">
            {% csrf_token %}
            {{ form|bulma }}
            <div class="field has-text-centered">
              <button class="button is-success is-rounded is*is-outlined" type="submit">{% trans "Valider" %}</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </section>
</div>

{% endblock %}

sud_education_vote/templates/changement_pwd_succes.html
{% extends 'base.html' %}

{% load i18n static %}

{% block content %}

<div class="container is-fluid">
  <section class="section">
    <div class="columns is-centered is-desktop mt-2">
      <div class="column is-half is-flex is-flex-direction-column is-align-items-center">
        <h1 class="title has-text-centered">
            {% trans "Mot de passe modifié avec succès" %}
        </h1>
        <p>
            {% trans "Votre mot de passe a été modifié." %}
        </p>
      </div>
    </div>
  </section>
</div>

{% endblock %}

sud_education_vote/templates/connexion.html
{% extends 'base.html' %}

{% load bulma_tags i18n %}

{% block content %}

<div class="container is-fluid">
  <section class="section">
    <div class="columns is-centered is-desktop mt-2">
      <div class="column is-half-desktop">
        <h1 class="title has-text-centered">{% trans "Connexion" %}</h4>
        <div class="box">
          <form class="form" method="post">
            {% csrf_token %}
            {{ form|bulma }}
            <div class="field has-text-centered">
              <button class="button is-success is-rounded is-outlined" type="submit">{% trans "Connexion" %}</button>
            </div>
          </form>
          <a href="{% url 'password_reset' %}">{% trans "Mot de passe oublié?" %}</a>
        </div>
      </div>
    </div>
  </section>
</div>

{% endblock %}

sud_education_vote/templates/deconnexion.html
{% extends 'base.html' %}

{% load i18n static %}

{% block content %}

<div class="container is-fluid">
  <section class="section">
    <div class="columns is-centered is-desktop mt-2">
      <div class="column is-half is-flex is-flex-direction-column is-align-items-center">
        <p>
          {% trans "Vous avez été déconnecté⋅e !" %}
        </p>
      </div>
    </div>
  </section>
</div>

{% endblock %}

sud_education_vote/templates/menu.html
{% load i18n static %}

<nav class="navbar" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <a class="navbar-item" href="/">
      <img src="{% static 'images/icon.jpg' %}">
    </a>

    <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="main-navbar">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>

  <div id="main-navbar" class="navbar-menu">
    <div class="navbar-start">
      {% if user.is_authenticated %}
        {% if user.is_superadmin %}
          <a class="navbar-item" href="{% url 'utilisateur:admins' %}">
            {% trans "Admins" %}
          </a>
          <a class="navbar-item" href="{% url 'vote:reinitialisation' %}">
            {% trans "Réinitialisation" %}
          </a>
        {% elif user.is_syndicat and not vote_admin %}
          <a class="navbar-item" href="{% url 'vote:page-vote' %}">
            {% trans "Vote" %}
          </a>
          <a class="navbar-item" href="{% url 'vote:scrutins' %}">
            {% trans "Scrutins"  %}
          </a>
          <a class="navbar-item" href="{% url 'vote:mes-votes' %}">
            {% trans "Mes votes"  %}
          </a>
        {% else %}
          {% if user.is_admin or vote_admin %}
            <a class="navbar-item" href="{% url 'utilisateur:syndicats' %}">
              {% trans "Syndicats" %}
            </a>
            <a class="navbar-item" href="{% url 'vote:scrutins' %}">
              {% trans "Scrutins"  %}
            </a>
            <a class="navbar-item" href="{% url 'vote:page-vote-admin' %}">
              {% trans "Voter pour un syndicat"  %}
            </a>
          {% endif %}
        {% endif %}
        <a class="navbar-item" href="{% url 'log:journal' %}">
          {% trans "Journal" %}
        </a>
      {% endif %}
    </div>
    <div class="navbar-end">
      {% if user.is_authenticated and not vote_admin %}
        <div class="navbar-item has-dropdown is-hoverable" >
          <a class="navbar-link">
            {{ user }}
          </a>
          <div class="navbar-dropdown is-boxed is-right">
            <a class="navbar-item" href="{% url 'password_change' %}">
              {% trans "Changement mot de passe" %}
            </a>
            <a class="navbar-item" href="{% url 'deconnexion' %}">
              {% trans "Déconnexion" %}
            </a>
          </div>
        </div>
      {% elif vote_admin %}
        <div class="navbar-item has-dropdown is-hoverable" >
          <a class="navbar-link">
            {{ admin }}
          </a>
        </div>
      {% else %}
          <a class="navbar-item" href="{% url 'connexion' %}" >
            {% trans "Connexion" %}
          </a>
      {% endif %}
    </div>
  </div>
</nav>

<script>
  document.addEventListener('DOMContentLoaded', () => {
    // Récuperer les éléments "navbar-burger"
    const $navbarBurgers = Array.prototype.slice.call(document.querySelectorAll('.navbar-burger'), 0);

    // Vérification de leurs existance
    if ($navbarBurgers.length > 0) {

      // On ajoute un événement pour chacun d'eux
      $navbarBurgers.forEach( el => {
        el.addEventListener('click', () => {

          // On récuperer la cible du navbar-burger via l'attribut target
          const target = el.dataset.target;
          const $target = document.getElementById(target);

          // Toggle la class "is-active" sur la cible et sur le navbar-burger
          el.classList.toggle('is-active');
          $target.classList.toggle('is-active');

        });
      });
    }

  });
</script>

sud_education_vote/templates/messages.html
{% if messages %}
<div class="columns is-centered is-vcentered">
    <div class="column is-half">
        <div class="container">
            {% for message in messages %}
                {% if message.tags == 'success' %}
                <div class="notification is-success">
                    <button class="button is-rounded is-success delete">X</button>
                {% elif message.tags == 'error' %}
                <div class="notification is-danger">
                    <button class="button is-rounded is-danger delete">X</button>
                {% elif message.tags == 'warning' %}
                <div class="notification is-warning">
                    <button class="button is-rounded is-warning delete">X</button>
                {% elif message.tags == 'info' %}
                <div class="notification is-info">
                    <button class="button is-rounded is-info delete">X</button>
                {% else %}
                <div class="notification is-primary"></div>
                    <button class="button is-rounded is-primary delete">X</button>
                {% endif %}
                    {{ message }}
                </div>
            {% endfor %}
        </div>
    </div>
</div>


<script>
document.addEventListener('DOMContentLoaded', () => {
    (document.querySelectorAll('.notification .delete') || []).forEach(($delete) => {
        const $notification = $delete.parentNode;
        $delete.addEventListener('click', () => {
            $notification.parentNode.removeChild($notification);
        });
    });
});
</script>

{% endif %}

sud_education_vote/templates/reinitialisation_password.html
{% extends 'base.html' %}

{% load bulma_tags i18n %}

{% block content %}

<div class="container is-fluid">
  <section class="section">
    <div class="columns is-centered is-desktop mt-2">
      <div class="column is-half-desktop">
        <h1 class="title has-text-centered">{% trans "Demande de réinitialisation de mot de passe" %}</h4>
        <div class="box">
          <form class="form" method="post">
            {% csrf_token %}
            {{ form|bulma }}
            <div class="field has-text-centered">
              <button class="button is-success is-rounded is-outlined" type="submit">{% trans "Réinitialiser mon mot de passe" %}</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </section>
</div>

{% endblock %}

sud_education_vote/templates/reinitialisation_password_complete.html
{% extends 'base.html' %}

{% load i18n %}

{% block content %}

<div class="container is-fluid">
  <section class="section">
    <div class="columns is-centered is-desktop mt-2">
      <div class="column is-half-desktop">
        <h1 class="title has-text-centered">{% trans "Changement de mot de passe" %}</h4>
        <div class="box">
            <p>Votre mot de passe a été modifié avec succès!</p>
        </div>
      </div>
    </div>
  </section>
</div>

{% endblock %}

sud_education_vote/templates/reinitialisation_password_confirm.html
{% extends 'base.html' %}

{% load bulma_tags i18n %}

{% block content %}

<div class="container is-fluid">
  <section class="section">
    <div class="columns is-centered is-desktop mt-2">
      <div class="column is-half-desktop">
        <h1 class="title has-text-centered">{% trans "Changement de mot de passe" %}</h4>
        <div class="box">
          <form class="form" method="post">
            {% csrf_token %}
            {{ form|bulma }}
            <div class="field has-text-centered">
              <button class="button is-success is-rounded is-outlined" type="submit">{% trans "Valider" %}</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </section>
</div>

{% endblock %}

sud_education_vote/templates/reinitialisation_password_done.html
{% extends 'base.html' %}

{% load i18n %}

{% block content %}

<div class="container is-fluid">
  <section class="section">
    <div class="columns is-centered is-desktop mt-2">
      <div class="column is-half-desktop">
        <h1 class="title has-text-centered">{% trans "Demande de réinitialisation de mot de passe" %}</h4>
        <div class="box">
            <p>L'email de réinitialisation de mot de passe vous a été envoyé. Veuillez cliquer sur le lien contenu dans l'email pour continuer.</p>
        </div>
      </div>
    </div>
  </section>
</div>

{% endblock %}