sud_education_vote/urls.py
from django.contrib import admin
from django.contrib.auth.views import (
    LogoutView,
    PasswordChangeDoneView,
    PasswordChangeView,
    PasswordResetCompleteView,
    PasswordResetConfirmView,
    PasswordResetDoneView,
    PasswordResetView,
)
from django.urls import include, path

from .views import AccueilView, ConnexionView

urlpatterns = [
    path("", AccueilView.as_view(), name="accueil"),
    path(
        "connexion/",
        ConnexionView.as_view(),
        name="connexion",
    ),
    path(
        "connexion/password_reset/",
        PasswordResetView.as_view(template_name="reinitialisation_password.html"),
        name="password_reset",
    ),
    path(
        "connexion/password_reset_done/",
        PasswordResetDoneView.as_view(
            template_name="reinitialisation_password_done.html"
        ),
        name="password_reset_done",
    ),
    path(
        "connexion/password_reset/confirm/<uidb64>/<token>/",
        PasswordResetConfirmView.as_view(
            template_name="reinitialisation_password_confirm.html"
        ),
        name="password_reset_confirm",
    ),
    path(
        "connexion/password_reset/done/",
        PasswordResetCompleteView.as_view(
            template_name="reinitialisation_password_complete.html"
        ),
        name="password_reset_complete",
    ),
    path(
        "deconnexion/",
        LogoutView.as_view(template_name="deconnexion.html"),
        name="deconnexion",
    ),
    path("admin/", admin.site.urls),
    path("utilisateurs/", include("sud_education_vote.utilisateur.urls")),
    path("votes/", include("sud_education_vote.vote.urls")),
    path("logs/", include("sud_education_vote.log.urls")),
    path(
        "changement-mot-de-passe/",
        PasswordChangeView.as_view(template_name="changement_pwd.html"),
        name="password_change",
    ),
    path(
        "changement-mot-de-passe-success/",
        PasswordChangeDoneView.as_view(template_name="changement_pwd_succes.html"),
        name="password_change_done",
    ),
]

sud_education_vote/utilisateur/urls.py
from django.urls import path

from .views import (
    AdminCreationView,
    AdminListView,
    AdminSupressionView,
    AdminUpdateView,
    ImportMandatsView,
    SyndicatCreateView,
    SyndicatListView,
    SyndicatSuppressionView,
    SyndicatUpdateView,
)

app_name = "utilisateur"

urlpatterns = [
    path("admins/", AdminListView.as_view(), name="admins"),
    path("admins/creation/", AdminCreationView.as_view(), name="admin-creation"),
    path(
        "admins/<int:pk>/edition/",
        AdminUpdateView.as_view(),
        name="admin-edition",
    ),
    path(
        "admins/<int:pk>/suppression/",
        AdminSupressionView.as_view(),
        name="admin-supression",
    ),
    path("syndicats/", SyndicatListView.as_view(), name="syndicats"),
    path("syndicats/creation/", SyndicatCreateView.as_view(), name="syndicat-creation"),
    path(
        "syndicats/<int:pk>/edition/",
        SyndicatUpdateView.as_view(),
        name="syndicat-edition",
    ),
    path(
        "syndicats/<int:pk>/suppression/",
        SyndicatSuppressionView.as_view(),
        name="syndicat-suppression",
    ),
    path("import-mandats/", ImportMandatsView.as_view(), name="import-mandats"),
]

sud_education_vote/utilisateur/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _

from .models import Utilisateur


class AdminCreationForm(forms.ModelForm):
    password = forms.CharField(
        max_length=255, label=_("Mot de passe"), widget=forms.PasswordInput()
    )
    confirm_password = forms.CharField(
        max_length=255, label=_("Confirm du mot de passe"), widget=forms.PasswordInput()
    )

    def clean_username(self):
        username = self.cleaned_data["username"]
        utilisateurs = Utilisateur.objects.filter(username=username)
        if utilisateurs.exists():
            raise ValidationError(
                "Il y a déjà un utilisateur avec ce nom d'utilisateur"
            )
        return username

    def clean_email(self):
        email = self.cleaned_data["email"]
        utilisateurs = Utilisateur.objects.filter(email=email)
        if utilisateurs.exists():
            raise ValidationError("Il y a déjà un utilisateur avec cet email")
        return email

    def clean(self):
        cleaned_data = super().clean()
        confirm_password = cleaned_data.get("confirm_password")
        if confirm_password != cleaned_data.get("password"):
            self.add_error(
                "confirm_password", _("Les mots de passe doivent être identiques")
            )
        return cleaned_data

    class Meta:
        model = Utilisateur
        fields = [
            "username",
            "email",
            "password",
        ]


class BaseForm(forms.ModelForm):
    password = forms.CharField(
        max_length=255, label=_("Mot de passe"), widget=forms.PasswordInput()
    )
    confirm_password = forms.CharField(
        max_length=255,
        label=_("Confirmation du mot de passe"),
        widget=forms.PasswordInput(),
    )

    _password = None

    def clean_username(self):
        username = self.cleaned_data["username"]
        utilisateurs = Utilisateur.objects.filter(username=username)
        if self.user:
            utilisateurs = utilisateurs.exclude(pk=self.user.pk)
        if utilisateurs.exists():
            raise ValidationError(
                "Il y a déjà un utilisateur avec ce nom d'utilisateur"
            )
        return username

    def clean_email(self):
        email = self.cleaned_data["email"]
        utilisateurs = Utilisateur.objects.filter(email=email)
        if self.user:
            utilisateurs = utilisateurs.exclude(pk=self.user.pk)
        if utilisateurs.exists():
            raise ValidationError("Il y a déjà un utilisateur avec cet email")
        return email

    def clean(self):
        cleaned_data = super().clean()
        confirm_password = cleaned_data.get("confirm_password")
        if confirm_password != cleaned_data.get("password"):
            self.add_error(
                "confirm_password", _("Les mots de passe doivent être identiques")
            )
        return cleaned_data

    def __init__(self, user, update, **kwargs):
        super().__init__(**kwargs)
        self.user = user
        if update:
            self.fields["password"].required = False
            self.fields["confirm_password"].required = False
            self._password = self.instance.password

    def save(self, commit=True):
        if self.cleaned_data.get("password"):
            self.instance.set_password(self.cleaned_data.get("password"))
        else:
            self.instance.password = self._password
        return super().save(commit=commit)

    class Meta:
        model = Utilisateur
        fields = []


class AdminUpdateForm(BaseForm):
    class Meta:
        model = Utilisateur
        fields = [
            "username",
            "email",
            "password",
        ]


class SyndicatForm(BaseForm):
    password = forms.CharField(
        max_length=255,
        label=_("Mot de passe (facultatif)"),
        widget=forms.PasswordInput(),
        required=False,
    )
    confirm_password = forms.CharField(
        max_length=255,
        label=_("Confirmation du mot de passe (facultatif)"),
        widget=forms.PasswordInput(),
        required=False,
    )

    class Meta:
        model = Utilisateur
        fields = [
            "username",
            "email",
            "nombre_mandat",
            "password",
        ]


class FichierImportMandatsForm(forms.Form):
    fichier = forms.FileField(label="Fichier d'import (.csv)")

sud_education_vote/utilisateur/views/gestion_admin_views.py
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views.generic import CreateView, DeleteView, ListView, UpdateView

from sud_education_vote.log.models import Log
from sud_education_vote.mixins import SuperAdminRequisMixin

from ..forms import AdminCreationForm, AdminUpdateForm
from ..models import Utilisateur


class AdminListView(SuperAdminRequisMixin, ListView):
    template_name = "utilisateur/liste_admins.html"
    model = Utilisateur

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(type_utilisateur=Utilisateur.ADMIN)
        return queryset


class AdminCreationView(SuperAdminRequisMixin, CreateView):
    model = Utilisateur
    form_class = AdminCreationForm
    template_name = "utilisateur/creation_admin.html"

    def form_valid(self, form):
        self.object = form.save()
        raw_password = self.object.password
        self.object.set_password(raw_password)
        self.object.type_utilisateur = Utilisateur.ADMIN
        self.object.save()
        Log.objects.create(log=f"Le super admin a créé l'admin {self.object}")
        return HttpResponseRedirect(self.get_success_url())

    def get_success_url(self):
        return reverse("utilisateur:admins")


class AdminUpdateView(SuperAdminRequisMixin, UpdateView):
    model = Utilisateur
    form_class = AdminUpdateForm
    template_name = "utilisateur/edition_admin.html"

    """
    On s'assure que l'utilisateur choisi est bien un admin
    """

    def get_queryset(self):
        return super().get_queryset().filter(type_utilisateur=Utilisateur.ADMIN)

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs.update({"user": self.get_object(), "update": True})
        return kwargs

    def get_success_url(self):
        return reverse("utilisateur:admins")


class AdminSupressionView(SuperAdminRequisMixin, DeleteView):
    model = Utilisateur
    template_name = "utilisateur/supression_admin.html"

    """
    On s'assure que l'utilisateur choisi est bien un admin
    """

    def get_queryset(self):
        return super().get_queryset().filter(type_utilisateur=Utilisateur.ADMIN)

    def delete(self, request, *args, **kwargs):
        Log.objects.create(log=f"Le super admin a supprimé l'admin {self.get_object()}")
        return super().delete(request, *args, **kwargs)

    def get_success_url(self):
        return reverse("utilisateur:admins")

sud_education_vote/utilisateur/views/gestion_syndicat_views.py
import codecs
import csv

from django.contrib import messages
from django.http import HttpResponseRedirect
from django.shortcuts import redirect, render
from django.urls import reverse
from django.views.generic import CreateView, DeleteView, ListView, UpdateView, View

from sud_education_vote.log.models import Log
from sud_education_vote.mixins import AdminRequisMixin

from ..forms import FichierImportMandatsForm, SyndicatForm
from ..models import Utilisateur


class SyndicatListView(AdminRequisMixin, ListView):
    template_name = "utilisateur/liste_syndicats.html"
    model = Utilisateur

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(type_utilisateur=Utilisateur.SYNDICAT)
        return queryset


class SyndicatCreateView(AdminRequisMixin, CreateView):
    model = Utilisateur
    template_name = "utilisateur/creation_syndicat.html"
    form_class = SyndicatForm

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs.update({"update": False, "user": None})
        return kwargs

    def get_success_url(self):
        return reverse("utilisateur:syndicats")

    def form_valid(self, form):
        self.object = form.save()
        self.object.type_utilisateur = Utilisateur.SYNDICAT
        self.object.save()
        Log.objects.create(
            log=f"L'admin {self.request.user} a créé le syndicat {self.object}"
        )
        return HttpResponseRedirect(self.get_success_url())


class SyndicatUpdateView(AdminRequisMixin, UpdateView):
    model = Utilisateur
    template_name = "utilisateur/edition_syndicat.html"
    form_class = SyndicatForm

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs.update({"update": True, "user": self.get_object()})
        return kwargs

    def get_queryset(self):
        return super().get_queryset().filter(type_utilisateur=Utilisateur.SYNDICAT)

    def get_success_url(self):
        return reverse("utilisateur:syndicats")

    def form_valid(self, form):
        previous_instance = Utilisateur.objects.get(pk=self.object.pk)
        self.object = form.save()
        if previous_instance.nombre_mandat != self.object.nombre_mandat:
            Log.objects.create(
                log=(
                    f"L'admin {self.request.user} a modifié "
                    f"le nombre de mandats du syndicat {self.object} "
                    f"de {previous_instance.nombre_mandat} à "
                    f"{self.object.nombre_mandat}"
                )
            )
        if previous_instance.email != self.object.email:
            Log.objects.create(
                log=(
                    f"L'admin {self.request.user} a modifié "
                    f"le mail du syndicat {self.object} "
                    f"de {previous_instance.email} à {self.object.email}"
                )
            )
        return HttpResponseRedirect(self.get_success_url())


class SyndicatSuppressionView(AdminRequisMixin, DeleteView):
    model = Utilisateur
    template_name = "utilisateur/suppression_syndicat.html"

    """
    On s'assure que l'utilisateur choisi est bien un syndicat
    """

    def get_queryset(self):
        return super().get_queryset().filter(type_utilisateur=Utilisateur.SYNDICAT)

    def delete(self, request, *args, **kwargs):
        Log.objects.create(
            log=f"L'admin {self.request.user} a "
            f"supprimé le syndicat {self.get_object()}"
        )
        return super().delete(request, *args, **kwargs)

    def get_success_url(self):
        return reverse("utilisateur:syndicats")


class ImportMandatsView(AdminRequisMixin, View):
    form_class = FichierImportMandatsForm
    template_name = "utilisateur/import_mandats.html"

    def get(self, request, *args, **kwargs):
        form = self.form_class()
        return render(request, self.template_name, {"form": form})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST, request.FILES)
        fichier = request.FILES["fichier"]
        if fichier.content_type == "text/csv":
            reader = csv.reader((codecs.iterdecode(fichier, "utf-8")))
            syndicats_erreur = []
            error = False
            for row in reader:
                if row[0] != "Syndicats":
                    syndicat = Utilisateur.objects.filter(
                        type_utilisateur=Utilisateur.SYNDICAT, username=row[0]
                    ).first()
                    if not syndicat or not row[1].isnumeric():
                        error = True
                        syndicats_erreur.append(row[0])
                    else:
                        syndicat.nombre_mandat = row[1]
                        syndicat.save()
            if error:
                messages.add_message(
                    self.request,
                    messages.WARNING,
                    (
                        f"Les lignes suivantes n'ont pas pu être ajoutées : "
                        f"{', '.join(syndicats_erreur)}. Vérifiez l'orthographe du nom"
                        f" du syndicat ou le nombre de mandats."
                    ),
                )
            return redirect(reverse("utilisateur:syndicats"))
        else:
            messages.add_message(
                self.request,
                messages.ERROR,
                ("Le fichier téléversé n'est pas au bon format"),
            )
            return render(request, self.template_name, {"form": form})

sud_education_vote/utilisateur/templates/utilisateur/creation_admin.html
{% extends 'base.html' %}

{% load bulma_tags i18n static %}

{% block content %}

<div class="container is-fluid">
  <div class="has-text-centered">
    <a class="mt-2 button is-info is-rounded is-outlined" href="{% url 'utilisateur:admins' %}">
      {% trans "Retour à la liste des admins" %}
    </a>
  </div>
  <section class="section">
    <div class="columns is-centered is-desktop">
      <div class="column is-half-desktop">
        <h1 class="title has-text-centered">{% trans "Création d'admin" %}</h1>
        <div class="box">
          <form class="form" method="post">
            {% csrf_token %}
            {{ form|bulma}}
            <div class="field has-text-centered">
              <button class="button is-success" type="submit">{% trans "Valider" %}</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </section>
</div>

{% endblock %}

sud_education_vote/utilisateur/templates/utilisateur/creation_syndicat.html
{% extends 'base.html' %}

{% load bulma_tags i18n static %}

{% block content %}

<div class="container is-fluid">
  <div class="hax has-text-centered">
    <a class="button is-info is-rounded is-outlined" href="{% url 'utilisateur:syndicats' %}">
      {% trans "Retour à la liste des syndicats" %}
    </a>
  </div>
  <section class="section">
    <div class="columns is-centered is-desktop">
      <div class="column is-half-desktop">
        <h1 class="title has-text-centered">{% trans "Création de syndicat" %}</h1>
        <div class="box">
          <form class="form" method="post">
            {% csrf_token %}
            {{ form|bulma}}
            <div class="field has-text-centered">
              <button class="button is-success is-rounded is-outlined" type="submit">{% trans "Valider" %}</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </section>
</div>

{% endblock %}

sud_education_vote/utilisateur/templates/utilisateur/edition_admin.html
{% extends 'base.html' %}

{% load bulma_tags i18n static %}

{% block content %}

<div class="container is-fluid">
  <div class="has-text-centered">
    <a class="button is-info is-rounded is-outlined" href="{% url 'utilisateur:admins' %}">
      {% trans "Retour à la liste des admins" %}
    </a>
  </div>
  <section class="section">
    <div class="columns is-centered is-desktop">
      <div class="column is-half-desktop">
        <h1 class="title has-text-centered">{% trans "Edition de l'admin" %} {{object}}</h1>
        <div class="box">
          <form class="form" method="post">
            {% csrf_token %}
            {{ form|bulma}}
            <div class="field has-text-centered">
              <button class="button is-success is-rounded is-outlined" type="submit">{% trans "Valider" %}</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </section>
</div>

{% endblock %}

sud_education_vote/utilisateur/templates/utilisateur/edition_syndicat.html
{% extends 'base.html' %}

{% load bulma_tags i18n static %}

{% block content %}

<div class="container is-fluid">
  <div class="has-text-centered">
    <a class="button is-info is-rounded is-outlined" href="{% url 'utilisateur:syndicats' %}">
      {% trans "Retour à la liste des syndicats" %}
    </a>
  </div>
  <section class="section">
    <div class="columns is-centered is-desktop">
      <div class="column is-half-desktop">
        <h1 class="title has-text-centered">{% trans "Edition du syndicat" %} {{object}}</h1>
        <div class="box">
          <form class="form" method="post">
            {% csrf_token %}
            {{ form|bulma}}
            <div class="field has-text-centered">
              <button class="button is-success is-rounded is-outlined" type="submit">{% trans "Valider" %}</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </section>
</div>

{% endblock %}

sud_education_vote/utilisateur/templates/utilisateur/import_mandats.html
{% extends 'base.html' %} {% load bulma_tags i18n static %} {% block content %}

<div class="container is-fluid">
	<div class="has-text-centered">
		<a
			class="button is-info is-rounded is-outlined"
			href="{% url 'utilisateur:syndicats' %}">
			{% trans "Retour à la liste des syndicats" %}
		</a>
	</div>
	<section class="section">
		<div class="columns is-centered is-desktop">
			<div class="column is-half-desktop">
				<h1 class="title has-text-centered">
					{% trans "Import des mandats" %}
				</h1>
				<p class="has-text-centered">
					Le nom du syndicat doit correspondre à celui déjà attribué à
					un syndicat. Le fichier importé doit être au format .csv et
					doit comprendre un en-tête et être structuré ainsi :
				</p>
				<div class="is-flex is-justify-content-center">
					<table class="table mt-3 is-bordered is-narrow">
						<thead>
							<tr>
								<th>Syndicats</th>
								<th>Mandats</th>
							</tr>
						</thead>
						<tbody>
							<tr>
								<td>Ain (01)</td>
								<td>67</td>
							</tr>
						</tbody>
					</table>
				</div>
				<div class="has-text-centered box m-6">
					<form
						class="form"
						method="post"
						enctype="multipart/form-data">
						{% csrf_token %} {{ form|bulma}}
						<div class="field has-text-centered">
							<button
								class="button is-success is-rounded is-outlined"
								type="submit">
								{% trans "Valider" %}
							</button>
						</div>
					</form>
				</div>
			</div>
		</div>
	</section>
</div>
<script>
	control = document.querySelector(".control");
	control.classList.add("is-flex");
	control.classList.add("is-justify-content-center");

	uploadIcon = document.querySelector(".fas");
	uploadIcon.classList.remove("fas");
	uploadIcon.classList.add("fa");
</script>

{% endblock %}

sud_education_vote/utilisateur/templates/utilisateur/liste_admins.html
{% extends 'base.html' %}

{% load i18n static %}

{% block content %}

<div class="container is-fluid">
    <section class="section">
        <h1 class="title has-text-centered">{% trans "Liste des admins" %}</h1>
        <div class="columns is-centered">
            <div class="column is-full has-text-centered">
                <a class="mb-2 button is-info is-rounded is-outlined" href="{% url 'utilisateur:admin-creation' %}">
                    <i class="fa fa-plus" aria-hidden="true"></i>
                </a>
                {% if object_list %}
                <div class="table-container">
                  <table class="table table-center is-fullwidth">
                      <thead>
                        <tr>
                          <th>{% trans "Nom" %}</th>
                          <th>{% trans "Email" %}</th>
                          <th>{% trans "Actions" %}</th>
                        </tr>
                      </thead>
                      <tbody>
                      {% for utilisateur in object_list %}
                          <tr>
                              <td>{{utilisateur.username}}</td>
                              <td>{{utilisateur.email}}</td>
                              <td>
                                <a href="{% url 'utilisateur:admin-edition' pk=utilisateur.pk %}">
                                    <button class="button is-info is-outlined">{% trans "Mise à jour" %}</button>
                                </a>
                                <a href="{% url 'utilisateur:admin-supression' pk=utilisateur.pk %}">
                                    <button class="button is-danger is-outlined">{% trans "Suppression" %}</button>
                                </a>
                              </td>
                          </tr>
                      {% endfor %}
                      </tbody>
                  </table>
                </div>
                {% else %}
                <h2 class="title is-5 has-text-centered">
                    {% trans "Il n'y a pas encore d'admins enregistrés!" %}
                </h2>
                {% endif %}
            </div>
        </div>
    </section>
</div>

{% endblock %}

sud_education_vote/utilisateur/templates/utilisateur/liste_syndicats.html
{% extends 'base.html' %}

{% load i18n static %}

{% block content %}

<div class="container is-fluid">
    <section class="section">
        <h1 class="title has-text-centered">{% trans "Liste des syndicats" %}</h1>
        <div class="columns is-centered">
            <div class="column is-full has-text-centered">
                <a class="button is-info my-2 mb-3 is-rounded is-outlined" href="{% url 'utilisateur:syndicat-creation' %}">
                    <i class="fa fa-plus" aria-hidden="true"></i>
                </a>
                <a class="button is-info my-2 mb-3 is-rounded is-outlined" href="{% url 'utilisateur:import-mandats' %}">
                    <i class="fa fa-upload p-2" aria-hidden="true"></i>Importer mandats
                </a>
                {% if object_list %}
                <div class="table-container">
                  <table class="table table-center is-fullwidth">
                      <thead>
                        <tr>
                          <th>{% trans "Nom" %}</th>
                          <th>{% trans "Email" %}</th>
                          <th>{% trans "Mandats" %}</th>
                          <th>{% trans "Action" %}</th>
                        </tr>
                      </thead>
                      <tbody>
                      {% for utilisateur in object_list %}
                          <tr>
                              <td>{{utilisateur.username}}</td>
                              <td>{{utilisateur.email}}</td>
                              <td>{{utilisateur.nombre_mandat}}</td>
                              <td class="has-text-left">
                                <a href="{% url 'utilisateur:syndicat-edition' pk=utilisateur.pk %}">
                                    <button class="button is-info is-outlined">{% trans "Mise à jour" %}</button>
                                </a>
                                <a href="{% url 'utilisateur:syndicat-suppression' pk=utilisateur.pk %}">
                                    <button class="button is-danger is-outlined">{% trans "Supprimer" %}</button>
                                </a>
                              </td>
                          </tr>
                      {% endfor %}
                      </tbody>
                  </table>
                </div>
                {% else %}
                <h2 class="title is-5 has-text-centered">
                    {% trans "Il n'y a pas encore de syndicats enregistrés!" %}
                </h2>
                {% endif %}
            </div>
        </div>
    </section>
</div>

{% endblock %}

sud_education_vote/utilisateur/templates/utilisateur/suppression_syndicat.html
{% extends 'base.html' %}

{% load bulma_tags i18n static %}

{% block content %}
  <div class="container is-fluid">
    <section class="section">
      <div class="has-text-centered">
        <a class="button is-info is-rounded is-outlined" href="{% url 'utilisateur:syndicats' %}">
          {% trans "Retour à la liste des syndicats" %}
        </a>
      </div>
      <h1 class="title mt-6 has-text-centered">{% trans "Suppression de syndicat" %}</h1>
      <div class="columns is-centered">
        <div class="column is-two-thirds">
          <div class="box m-6 has-text-centered">
            <form method="post" class="form has-text-centered">{% csrf_token %}
              <p class="m-2"><strong>{% trans "Êtes vous sûr·e·s de vouloir supprimer le syndicat "%} {{object}}?</strong></p>
              <input class="button is-danger is-outlined" type="submit" value="{% trans 'Confirmer' %}">
            </form>
          </div>
        </div>
      </div>
    </section>
  </div>
{% endblock %}

sud_education_vote/utilisateur/templates/utilisateur/supression_admin.html
{% extends 'base.html' %}

{% load bulma_tags i18n static %}

{% block content %}
  <div class="container is-fluid">
    <section class="section">
      <div class="has-text-centered">
        <a class="button is-info is-rounded is-outlined" href="{% url 'utilisateur:admins' %}">
          {% trans "Retour à la liste des admins" %}
        </a>
      </div>
      <h1 class="title has-text-centered">{% trans "Suppression d'admin" %}</h1>
      <div class="columns is-centered">
        <div class="column is-two-thirds">
          <div class="box m-6 has-text-centered">
            <form method="post" class="form has-text-centered">{% csrf_token %}
              <p class="m-2"><strong>{% trans "Êtes vous sûr·e·s de vouloir supprimer l'admin "%} {{object}}?</strong></p>
              <input class="button is-danger is-outlined" type="submit" value="{% trans 'Confirmer' %}">
            </form>
          </div>
        </div>
      </div>
    </section>
  </div>
{% endblock %}