sud_education_vote/log/urls.py
from django.urls import path

from .views import ExportTxtJournalView, JournalLogListView

app_name = "log"

urlpatterns = [
    path("journal/", JournalLogListView.as_view(), name="journal"),
    path("journal/export/", ExportTxtJournalView.as_view(), name="journal-export"),
]

sud_education_vote/urls.py
from django.contrib import admin
from django.contrib.auth.views import (
    LogoutView,
    PasswordChangeDoneView,
    PasswordChangeView,
    PasswordResetCompleteView,
    PasswordResetConfirmView,
    PasswordResetDoneView,
    PasswordResetView,
)
from django.urls import include, path

from .views import AccueilView, ConnexionView

urlpatterns = [
    path("", AccueilView.as_view(), name="accueil"),
    path(
        "connexion/",
        ConnexionView.as_view(),
        name="connexion",
    ),
    path(
        "connexion/password_reset/",
        PasswordResetView.as_view(template_name="reinitialisation_password.html"),
        name="password_reset",
    ),
    path(
        "connexion/password_reset_done/",
        PasswordResetDoneView.as_view(
            template_name="reinitialisation_password_done.html"
        ),
        name="password_reset_done",
    ),
    path(
        "connexion/password_reset/confirm/<uidb64>/<token>/",
        PasswordResetConfirmView.as_view(
            template_name="reinitialisation_password_confirm.html"
        ),
        name="password_reset_confirm",
    ),
    path(
        "connexion/password_reset/done/",
        PasswordResetCompleteView.as_view(
            template_name="reinitialisation_password_complete.html"
        ),
        name="password_reset_complete",
    ),
    path(
        "deconnexion/",
        LogoutView.as_view(template_name="deconnexion.html"),
        name="deconnexion",
    ),
    path("admin/", admin.site.urls),
    path("utilisateurs/", include("sud_education_vote.utilisateur.urls")),
    path("votes/", include("sud_education_vote.vote.urls")),
    path("logs/", include("sud_education_vote.log.urls")),
    path(
        "changement-mot-de-passe/",
        PasswordChangeView.as_view(template_name="changement_pwd.html"),
        name="password_change",
    ),
    path(
        "changement-mot-de-passe-success/",
        PasswordChangeDoneView.as_view(template_name="changement_pwd_succes.html"),
        name="password_change_done",
    ),
]

sud_education_vote/log/models.py
from django.db import models


class Log(models.Model):
    """
    Modele log : Chaque fois qu'un utilisateur fera une action,
    un log sera créé pour garder une trace
    """

    log = models.CharField(max_length=255)
    date_log = models.DateTimeField(auto_now_add=True)

sud_education_vote/log/views/log_journal_view.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.views.generic import ListView, View

from sud_education_vote.vote.models import Scrutin

from ..models import Log


class JournalLogListView(LoginRequiredMixin, ListView):
    template_name = "log/journal_logs.html"
    model = Log

    def dispatch(self, request, *args, **kwargs):
        scrutin_en_cours = Scrutin.objects.filter(ouvert=True).exists()
        if scrutin_en_cours:
            if not self.request.user.is_admin:
                messages.add_message(
                    self.request,
                    messages.ERROR,
                    (
                        "Un scrutin est en cours, vous ne pouvez"
                        " pas consulter les logs !"
                    ),
                )
                return HttpResponseRedirect(reverse("vote:scrutins"))
        return super().dispatch(request, *args, **kwargs)

    # On affiche les 200 derniers Logs
    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.order_by("-date_log")[:200]
        return queryset


class ExportTxtJournalView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        content = ""
        for log in Log.objects.all():
            date_str = log.date_log.strftime("%m/%d/%Y %H:%M:%S")
            content = content + f"{date_str} {log.log}\n"
        response = HttpResponse(
            content=content,
            content_type="text/plain",
            headers={"Content-Disposition": "attachment; filename=journal.txt"},
        )
        return response

sud_education_vote/log/templates/log/journal_logs.html
{% extends 'base.html' %}

{% load i18n static %}

{% block content %}

<div class="container is-fluid">
    <section class="section">
        <h1 class="title has-text-centered">{% trans "Journal des logs" %}</h1>
        <div class="columns is-centered">
            <div class="column is-full">
                {% if object_list %}
                    <div>
                        <a class="button is-success is-rounded is-outlined" href="{% url 'log:journal-export'%}">
                            {% trans "Export txt" %}
                        </a>
                    </div>
                    <div class="table-container">
                    <table class="table table-center is-fullwidth">
                        <thead>
                            <tr>
                            <th>{% trans "Date" %}</th>
                            <th>{% trans "Log" %}</th>
                            </tr>
                        </thead>
                        <tbody>
                        {% for log in object_list %}
                            <tr>
                                <td>{{log.date_log}}</td>
                                <td>{{log.log}}</td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                    </div>

                {% else %}
                    <h2 class="title is-5 has-text-centered">
                        {% trans "Il n'y a pas encore de logs enregistrés!" %}
                    </h2>
                {% endif %}
            </div>
        </div>
    </section>
</div>

{% endblock %}